### ISSUE TITLE
cannot find module oidc-client

### ISSUE THREAD

**Issue by crh225** [jmurphzyo/Angular2OidcClient#1]
Hi! I have typescript version 2.0.0 installed, ran the install, then ng -b and get the following error.

![image](https://cloud.githubusercontent.com/assets/19475195/17789559/5beb8e5c-6558-11e6-8a58-904a30c04a63.png)

**Comment by crh225** [comment]
Great work BTW!

**Comment by jmurphzyo** [comment]
@crh225  did you do this part? `I added an extra folder to the project oidc-client-@types copy the contents of that folder, then navigate to node_modules/@types. Create a folder inside the @types folder named oidc-client and paste the copied contents inside` . Also you have to make sure that tsc is pointed at 'node_modules/typescript/lib` if you don't have typescript 2 installed globally.

**Comment by jmurphzyo** [comment]
@crh225 going to close this for now. If what I posted above doesn't fix the issue let me know and I will take another look at it.

**Comment by Neftedollar** [comment]
I've got the same error with the current version. 
Typescript version 2.0.0.
As I understand, I shouldn't create node_modules/@types/oidc-types

**Comment by jmurphzyo** [comment]
@Neftedollar With the OIDC client the extra steps aren't needed, just rename the oidc-client.d.ts to index.d.ts. The file will be located in node_modules/oidc-client/.

**Comment by Neftedollar** [comment]
ok, thank's, i'll try it.
