### ISSUE TITLE
AuthGet and the order of operations

### ISSUE THREAD

**Issue by paqogomez** [jmurphzyo/Angular2OidcClient#10]
Are there examples of using AuthGet, AuthPut and such?  The "_setAuthHeaders" method in auth.server.ts isnt wired up to anything that I can see.

**Comment by jmurphzyo** [comment]
@paqogomez sorry, I have been busy. I will look at  _setAuthHeaders next week. If you want to issue a pr with an implementation of a simple backend api that implements OIDC. I will create the views/calls for the angular side.

**Comment by bvanbleyenbergh** [comment]
_setAuthHeaders method is still not wired up to anything?

**Comment by jmurphzyo** [comment]
[e201b36 ](https://github.com/jmurphzyo/Angular2OidcClient/commit/154d0e073a823150ae25dafde5fcb773277c8475)
