### ISSUE TITLE
oidc-client.min.js

### ISSUE THREAD

**Issue by muena** [jmurphzyo/Angular2OidcClient#11]
Hi,

First of all: great work!
I have just one question: I couldn't find out which version of oidc-client-js you are using.
It just works fine, but your oidc-client.min.js is different from all tagged versions of oidc-client.min.js from IdentityModel.

**Comment by jmurphzyo** [comment]
its an old version. What I recommend doing is after you run npm install just copying the oidc-client.min.js from the node_modules.

**Comment by muena** [comment]
My problem was that I had serious troubles (Frame window timed out) with silent login when using a current version of oidc-client.min.js.
After using your version, everything is working again.

**Comment by jmurphzyo** [comment]
post which version you're using. I haven't looked at the new changes they have made to oidc-client lately.

**Comment by muena** [comment]
Sorry, please forget that.

I have just tried to use the newest version of oidc-client-js again and it works!
I had problems over the last few days with the "Frame window timed out error" and tried everything.

At first i thought that the problem was with the version of oidc-client.min.js but I think it was related to the webpack-dev-server.
