### ISSUE TITLE
Logout configuration

### ISSUE THREAD

**Issue by sankp** [jmurphzyo/Angular2OidcClient#13]
Hello,

I am using your code for login using identity server.
I am able to make logout working but how can i redirect back to my application main page after logout.

```
const settings: any = {
    authority: "https://Machinename/IdentityServerAuth',
    client_id: 'ApplicationName',
    redirect_uri:  "https://Machinename/ApplicationName" + '/public/auth.html',
    silent_redirect_uri: "https://Machinename/ApplicationName"  + '/public/silent-renew.html', 
    post_logout_redirect_uri: "https://Machinename/ApplicationName" + '/public/signout-callback.html', 
    response_type: 'id_token token',
    scope:  'openid email'
    automaticSilentRenew: true,
    silentRequestTimeout: 10000,
    filterProtocolClaims: true,
    loadUserInfo: true
};
```

This is what i am using so it will be great if u can guide where exactly i need to provide application url.

**Comment by jmurphzyo** [comment]
@sankp that will be handled by the identity server. If you know your identity server is setup correctly to handle the redirects then you will need to post an issue on the oidc-client repo and make sure they are passing the correct info to the logout endpoint. Let me know what you find out!

**Comment by sankp** [comment]
Hello,

I also raise issue here
https://github.com/IdentityModel/oidc-client-js/issues/292

So far no response yet. but if u see the screenshot of mine. ng-model is not getting those urls needed.

**Comment by jmurphzyo** [comment]
@sankp Did you end up finding out the issue? going to close for now since its not relevant to this demo.
