### ISSUE TITLE
Question: Have you tried your solution with angular 4.0 ?

### ISSUE THREAD

**Issue by StephanHartmann** [jmurphzyo/Angular2OidcClient#14]
Hi, may I  ask you, if you hav eupgraded your solution already to angular 4.0 ?

I use a similar apporach with oidc client and a auth.html.
Since I switched to angular 4 it is not working anymore.
The redirect to identity server works fine, but when I signed in and get redirected to auth.html
I get the following error:

![ang4](https://cloud.githubusercontent.com/assets/10873640/24367286/5e7871c2-131c-11e7-8110-30e5573feedb.png)

I have no idea why this is happening :(
Is it a bug in angular router ?

**Comment by yousufali** [comment]
@StephanHartmann  You need to add auth.html to assets in angular-cli.json file.

**Comment by StephanHartmann** [comment]
I already tried that, but it is not working.
I use Google Chrome to test it, and what I now noticed is really weird ...
the dev tools show me a auth.html with the content of index.html ...

I use angular cli 1.0.0

**Comment by yousufali** [comment]
I had similar issue when upgrading to angular cli 1.0 . I was able to get it working with minor tweaks, I will submit a PR so you can take a look.

**Comment by StephanHartmann** [comment]
@yousufali thanks, it is working now :)
sometimes its a problem of reading what others wrote :(

I read your first post and copied auth.html to assets folder ...
My Mind totally ignored the mentioned angular-cli.json file.

After adding it in the file (and restarting ng serve) it works.
Once again, Thank you :)
