### ISSUE TITLE
Does silentRenew work with this library?

### ISSUE THREAD

**Issue by sstorie** [jmurphzyo/Angular2OidcClient#17]
First off, thanks for putting this together and sharing. 

I'm trying to get it to work using the ng4 branch you've set up. The only thing not working so far is automatic silent renewal of the tokens. What appears to be happening is the renewal works fine, but the Angular instance of UserManager never sees the event it needs to know the iframe requests are succeeding. I suspect this is because the redirect response is handled in another instance of UserManager created in a static html page. I updated the code slightly to use a different callback page for the silent renewal as in [this example](https://github.com/IdentityModel/oidc-client-js/blob/dev/sample/public/user-manager-sample-silent.html).

I'm working to debug this, but was curious if anyone has gotten this to work? 

Here's a another issue that seems related (just for reference):
https://github.com/IdentityModel/oidc-client-js/issues/250#issuecomment-276610326

**Comment by jmurphzyo** [comment]
@sstorie I haven't tested the silent renew part but If I had to guess I will need to notify angular that it exists outside the angular app using [NgZone](https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html)

**Comment by sstorie** [comment]
Ok, thanks for clarifying. I'm going to keep digging here to both build my understanding of how oidc-client-js works and hopefully be able to submit a PR back to this project.

So far it seems that when the silent re-direct happens the interaction with IdentityServer (in my case) work okay, but that's all handled within a hidden iframe next to the original Angular application. From what I can tell so far, the oidc library opens a second iframe that monitors the session data stored, and periodically posts a message back to the parent window indicating if the session data has changed or not. When we do a slient renew, the oidc code is looking for an indication that the session data has changed to know the user updated properly, and if it doesn't get it then it throws the timeout error.

Here's what I see in in the midst of this process:

![image](https://cloud.githubusercontent.com/assets/3630784/25088675/a769b928-233d-11e7-8c35-e6ad99e5fada.png)


![image](https://cloud.githubusercontent.com/assets/3630784/25088402/bd39d21c-233b-11e7-810e-3374d9fc63f0.png)

I'm still new to how iframes and posting messages work, but if I expand down that silent renew iframe I can see my static html page loaded, but also that *it* opens another "checksession" iframe to monitor the session data:

![image](https://cloud.githubusercontent.com/assets/3630784/25088555/c7312260-233c-11e7-8f1b-9d1b6f1486f8.png)

So I don't know yet if this "iframe within an iframe" situation is causing a problem or not, but I'll keep digging. It's possible that there will be a zone issue with Angular too, but from reading the logs written by oidc-client-js I think the issue is still happening at a lower level right now.

**Comment by sstorie** [comment]
Doh!

I think I found my problem....I'm not using the right function in my silent renewal html page.

![image](https://cloud.githubusercontent.com/assets/3630784/25089271/c975256c-2341-11e7-908f-041e11ba7327.png)

Here's the proper HTML for the silent renewal callback:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title></title>
</head>

<body>
    <h1 id="waiting">Waiting...</h1>

    <div id="error">

    </div>
    <script src="oidc-client.js"></script>
    <script>
        Oidc.Log.logger = console;
        Oidc.Log.level = 4;

        new Oidc.UserManager().signinSilentCallback();
    </script>
</body>

</html>
```

I'll close this ticket now.
