### ISSUE TITLE
TypeScript error :  'A class member cannot be declared optional.'

### ISSUE THREAD

**Issue by tomadj** [jmurphzyo/Angular2OidcClient#18]
Hello, 

I have an typsescript error on build by the angular-cli : 

TypeScript error:  /angular2Client/node_modules/oidc-client/oidc-client.d.ts(32,15): Error TS1112: A class member cannot be declared optional. 

My oidc import in my authSerice : 
`
import { UserManager, User } from 'oidc-client';`

any idea ? 

I have the same error when I build this repo

Thank's

**Comment by jmurphzyo** [comment]
which branch is that from? I need to update the tslint/tsconfig.

**Comment by jmurphzyo** [comment]
@tomadj try the new package notice the change on the [tslint.json](https://github.com/jmurphzyo/Angular2OidcClient/blob/master/tslint.json#L51-L52)

**Comment by tomadj** [comment]
The ng4 branch ! I will try. 
Thank's
