### ISSUE TITLE
Using with Google

### ISSUE THREAD

**Issue by TayBill** [jmurphzyo/Angular2OidcClient#19]
Hmm, I'm very much a novice, so this could be a dumb or misdirected question.

 I wanted to try to connect this to google, just as a test.
From google, I have a "clientId" and a "clientSecret".

Can you tell me how those match to settings of authority, clientId etc, as defined in auth.service.ts  
I tried multiple combinations, with no luck.

**Comment by jmurphzyo** [comment]
you would need to ask that in the oidc-client.js lib. I don't know if they have a gitter room or not.
