### ISSUE TITLE
Browser refresh results in redirect to unauthenticated

### ISSUE THREAD

**Issue by sigged** [jmurphzyo/Angular2OidcClient#21]
I'm trying to implement OidClient so I'm studying this great example app. Now I've come across an issue where the app redirects me to _/unauthenticated_ even though I should have a token. Steps to reproduce:

1. When visiting _protected_ without being authed, click on "Unauthorized Request to login click here."
2. Authenticate with the OpenID server, then click on the routerLink to "protected"
3. The page is now displaying the contents of _protected_ correctly
4. Refreshing the protected page with F5 results in a redirect to _unauthenticated_

I'm trying to find what I'm missing here with some breakpoints, one in AuthGuardService and one AuthService. I noticed the following: when hitting F5, the AuthGuardService checks  `this.authService.loggedIn` before AuthService has the chance to set `loggedIn = true` in its constructor, causing the redirect.

Am I overlooking something or is this behavior a bug?

**Comment by jmurphzyo** [comment]
I will look into it but I am guessing when the app reloads the guard is being called before the promises are able to resolve in the auth service.

**Comment by sigged** [comment]
I managed to fix this by adding a function to the AuthService:

    isLoggedIn(): Observable<boolean> {
      return Observable.fromPromise(this.mgr.getUser()).map<User, boolean>((user) => {
        if (user) return true;
        else return false;
      });
    }

And then use the following CanActivate implementation:

    canActivate() {
        let self = this;
        let isloggedIn = this.authService.isLoggedIn();
        isloggedIn.subscribe((loggedin) => {
            if(!loggedin){
                self.router.navigate(['unauthorized']);
            }
        });
        return isloggedIn;
    }

This canActivate implementation returns an Observable<boolean> instead of a boolean, to let it wait for the Promise in the AuthService to complete. There is also a subscription so we can decide whether to redirect to _unauthorized_ or not.
This fixes this particular problem, but any other ideas welcome!

**Comment by jmurphzyo** [comment]
[#d14ae20](https://github.com/jmurphzyo/Angular2OidcClient/commit/d14ae20ca1183bae83d24c591b1a4ca4d6b53e2e)
