### ISSUE TITLE
ng4 branch not working

### ISSUE THREAD

**Issue by ghost** [jmurphzyo/Angular2OidcClient#22]
auth.html gives a 404 on assets/oidc-client.min.js.  This can be fixed by either changing

`        {"glob":"**/*.js", "input":"../node_modules/oidc-client/dist/","output":"./"},`
to
`       {"glob":"**/*.js", "input":"../node_modules/oidc-client/dist/","output":"./assets"},`
in .angular-cli.json

or 
`<script src="assets/oidc-client.min.js"></script>`
to 
`<script src="oidc-client.min.js"></script>`
in auth.html

However after fixing this I'm then stumped by the error "Log is not defined" after the auth redirect.

**Comment by jmurphzyo** [comment]
Whoops sorry, I didn't test the client before I pushed the update. Thanks for letting me know [#7ae61af](https://github.com/jmurphzyo/Angular2OidcClient/commit/7ae61af4138d4ad00cec69c06b8919c83e51e7d9)

**Comment by jmurphzyo** [comment]
I don't know if the oidc-client.min version has the Log named something different but I pushed an update that commented out the Log.logger = console; I am guessing that should fix the issue. [#7ae61af](https://github.com/jmurphzyo/Angular2OidcClient/commit/e84edbecb4599fc3c6041208e5747ab8b9aba3b3)

**Comment by jmurphzyo** [comment]
ee1c5d5  be7d893
