### ISSUE TITLE
UserManager not defined

### ISSUE THREAD

**Issue by cxc256** [jmurphzyo/Angular2OidcClient#28]
When clicking on the startSigninMainWindow button and after logging in through my IdentityServer implementation, I get a javascript error that UserManager is not defined on Auth.html/Auth.js

**Comment by 0xGeorgii** [comment]
Fixed

**Comment by jmurphzyo** [comment]
@GeorgePlotnikov

**Comment by ChrisDevinePimss** [comment]
Am getting this too in the ng4 version
