### ISSUE TITLE
update auth.service.ts to use User interface 

### ISSUE THREAD

**Issue by crh225** [jmurphzyo/Angular2OidcClient#3]
In the typings for oidc, there is a user interface. You can import it at the top of the **auth.service.ts**
import { UserManager, Log, MetadataService, User } from 'oidc-client';

You can close this, I just wanted to make an enhancement suggestion.

**Comment by jmurphzyo** [comment]
https://github.com/jmurphzyo/Angular2OidcClient/commit/7ca0e0fb8a16f46b8bf0b05986b4f20b8d2dc3f9

**Comment by jmurphzyo** [comment]
@crh225 I do have a question for you though. After you authenticate would you mind checking in your documents main body and telling me how many check session iframes are generated?

**Comment by crh225** [comment]
@jmurphzyo I'll check it out tomorrow when I get to work.

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/18006172/f2c76e8e-6b63-11e6-828f-0e3e19b9346a.png)

I checked through the collapased tags also and did not see any other iframes. Note I am not using silent signin....yet.

Currently I am using the auth.service.ts to do autologin this way:
![image](https://cloud.githubusercontent.com/assets/19475195/18006234/3b978770-6b64-11e6-8997-dd3f2f7edccd.png)

**Comment by jmurphzyo** [comment]
I am guessing you're redirecting to the app root and not an external html file?

**Comment by jmurphzyo** [comment]
well local to the domain but external from the angular app

**Comment by crh225** [comment]
currently yes, I was just trying to get the base case working. Now I am working on the silent iFrameLogin.

```
            this.mgr.signinSilent({ scope: 'openid profile email api1', response_type: 'id_token token' }).then((user) => {
                console.log("signed in", user);
                this.loggedIn = true;
                //this._user = <User>user.profile;
                this._user = user;
                this.token = this._user.access_token;
                //alert("user exists");
                this.userLoadededEvent.emit(user);
            }).catch(function (err) {
                this.loggedIn = false;
                console.log(err);
            });
```

**Comment by jmurphzyo** [comment]
Yeah, I just noticed I am getting two iframe instances redirecting to the html I am going to try something a little different and redirect to the index.html file. If we redirect directly to the app without referencing a html file the browser history will reflect the token.

**Comment by crh225** [comment]
You are getting it with the code on github, or code you havent pushed?

**Comment by jmurphzyo** [comment]
In one of the applications I am building, the setup is pretty similar to this setup. I am about to run this project as is and see if its the same result.

**Comment by jmurphzyo** [comment]
@crh225 I figured it out I was testing the usermanager.events.load(); and it was creating another iframe instance. Just wasted my entire morning figuring that out.

**Comment by crh225** [comment]
@jmurphzyo for what it is worth, I have gotten my login down to the following lines of code. it uses the silent iframe login. I don't know if it is 1000 percent correct, but for my purpose, it will do for now. 

![image](https://cloud.githubusercontent.com/assets/19475195/18018343/e9a32d4c-6b9b-11e6-9d8d-c7f4dee22a5e.png)

**Comment by jmurphzyo** [comment]
With that setup does the silent sign in issue a redirect if the user isn't stored? and if it is stored refresh the token?

**Comment by crh225** [comment]
@jmurphzyo ,the routes do the redirecting with the authgaurd if logged in is false. If my user object does not exist, if have a ngif wrapping my html to only show if user is populated and bound.
