### ISSUE TITLE
Feel lost in the codes: signinRedirect() vs signinSilent()

### ISSUE THREAD

**Issue by alvachien** [jmurphzyo/Angular2OidcClient#33]
Based on #17, you mentioned the SPA didn't received the notification.
But it focused me deeply.

Based on your codes in this repo (https://github.com/jmurphzyo/Angular2OidcClient/blob/master/src/app/shared/services/auth.service.ts), you will call singinRedirect() for the first sign-in, correct?
Then, when shall call to signinSilent()? Or, am I totally wrong?

Thank you so much in advance, Alva

**Comment by jmurphzyo** [comment]
sorry for the delayed response. The signinSilent would be called if you wanted to resign in a user with them being redirected away from the app.
