### ISSUE TITLE
localStorage Problem

### ISSUE THREAD

**Issue by ibrahimsen** [jmurphzyo/Angular2OidcClient#36]
Thank you for your oidc-client angular example. when I change config to **userStore: new WebStorageStateStore({ store: localStorage})**  It does not work as expected. Could you please assist the problem.

**Comment by jmurphzyo** [comment]
I would imagine that has something to do with the OIDC library this project utilizes. I haven't kept up the current versioning of that project. Also I have not attempted to do that override using angular 2/4
