### ISSUE TITLE
use of Angular2OidcClient in VisualStudio Project

### ISSUE THREAD

**Issue by sankp** [jmurphzyo/Angular2OidcClient#5]
Hello,

I am able to make this project work on my machine using angular cli build and using my custom IdentityServer on localhost.
Now i am trying to use this project by copying required files to VisualStudio based project which uses VisualStudio build to create dist bundles.
i am using this way in index.html

    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="systemjs.config.js"></script> 

How can i include odic-client.js in this?
Any sample solution will be helpful.

my systemjs.config looks like this

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },    
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
     
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
  });
})(this);

and this is package.json

{
  "name": "ng2-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "pree2e": "npm run webdriver:update",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/common": "~2.1.2",
    "@angular/compiler": "~2.1.2",
    "@angular/core": "~2.1.2",
    "@angular/forms": "~2.1.2",
    "@angular/http": "~2.1.2",
    "@angular/platform-browser": "~2.1.2",
    "@angular/platform-browser-dynamic": "~2.1.2",
    "@angular/router": "~3.1.2",
    "@angular/upgrade": "~2.1.2",

    "angular-in-memory-web-api": "~0.1.13",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "oidc-client": "^1.2.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "concurrently": "^3.1.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3",

    "canonical-path": "0.0.2",
    "http-server": "^0.9.0",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.4",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-script-launcher": "~0.1.0",
    "karma-html2js-preprocessor": "~0.1.0",
    "protractor": "4.0.9",
    "webdriver-manager": "10.2.5",
    "rimraf": "^2.5.4",

    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.46",
    "@types/jasmine": "^2.5.36",
    "@types/selenium-webdriver": "^2.53.33"
  },
  "repository": {}
}

**Comment by jmurphzyo** [comment]
@sankp I haven't tested this but from what it looks like you will only need to change two things. First, in the system.js file where you have // other libraries you will need to include the oidc-client which would look something like this

``` javascript
// other libraries
'rxjs': 'npm:rxjs',
'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
`oidc-client':'npm:oidc-client/dist/oidc-client.js'
```

Second, you will need to change your index.html to include the oidc-client.js file and this part you might need to tinker because I think the order of where it is included might be important. This is what I would try first.

``` html
<script src="node_modules/core-js/client/shim.min.js"></script>
<script src="node_modules/oidc-client/dist/oidc-client.js"></script>
<script src="node_modules/zone.js/dist/zone.js"></script>
<script src="node_modules/reflect-metadata/Reflect.js"></script>
<script src="node_modules/systemjs/dist/system.src.js"></script>
<script src="systemjs.config.js"></script>
```

Let me know if you get it working or not.

**Comment by sankp** [comment]
Hello,

I am able to make this work now using this 'npm:oidc-client/lib/oidc-client.js' in systemjs.config.js file thats all.

**Comment by figuerres** [comment]
@sankp : what about babel-polyfill ?  did you add that to your app or not ?
if you did how did you configure for it ?
it is listed as a dependancy but i have not found any info on how to edit systemjs for that package and when i did add it i had errors trying to run the app.

**Comment by sankp** [comment]
@figuerres i didn't try that as i was getting different errors earlier but after referencing as mentioned above 
i am able to make it work referencing from lib folder.

**Comment by figuerres** [comment]
as soon as the browser refers to the oidc client i get an error that something is not defined but i do not know what it is erroring on really.... trying to find out what that is.
i am trying to use the code from this sample and the error is when it is in https://github.com/jmurphzyo/Angular2OidcClient/blob/master/src/app/shared/services/auth.service.ts

`localhost/:28 Error: (SystemJS) AMD module http://localhost:3000/node_modules/oidc-client/dist/oidc-client.js did not define
	TypeError: AMD module http://localhost:3000/node_modules/oidc-client/dist/oidc-client.js did not define
	    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:232:26)
	    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:114:43)
	    at http://localhost:3000/node_modules/zone.js/dist/zone.js:502:57
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:401:35)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:339:25)
	Error loading http://localhost:3000/node_modules/oidc-client/dist/oidc-client.js as "oidc-client" from http://localhost:3000/app/shared/services/auth.service.js
	    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:232:26)
	    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:114:43)
	    at http://localhost:3000/node_modules/zone.js/dist/zone.js:502:57
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:401:35)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:339:25)
	Error loading http://localhost:3000/node_modules/oidc-client/dist/oidc-client.js as "oidc-client" from http://localhost:3000/app/shared/services/auth.service.js`

**Comment by figuerres** [comment]
ok when i refer to the shared\services\authservice.ts file that is ok but when i add the  auth-guard.service.ts then i get the error above...
`   providers:
     [
        authProviders
    ],`

i add that in my app.module.ts in my @NgModule({})   and boom!

**Comment by sankp** [comment]
import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';

import { AuthService } from './auth.service';

@Injectable()
export class AuthGuardService implements CanActivate {

    constructor(private authService: AuthService, private router: Router) { }
    canActivate() {
        if (this.authService.loggedIn) { return true; }
        this.router.navigate(['unauthorized']);

    }

}

**Comment by sankp** [comment]
I have that in app.module.ts too

**Comment by figuerres** [comment]
Hey sorry i meant to post here yesterday,  i got my code working and i will be making a sample to upload and share now that i got it to work.
