### ISSUE TITLE
adapting this sample to using systemjs and light server

### ISSUE THREAD

**Issue by figuerres** [jmurphzyo/Angular2OidcClient#6]
I am new with angular 2 and my web app right now is using systemjs and light server.
so i am trying to adopot what you have to work for me.

I have most of the files added to my project and the typescript compiler is happy.
but at runtime i see s couple of 404 errors.
404 get /traceur
404  get  /app/aunauthorized.js

but i am not sure what the error mean in terms of bringing in your code and the related changes i need to make.

if you could possibly make a sample that is using system js and light server that would be great!
then it would help me see if i am lacking some things.
i am wondering about the polyfills and the babel stuff ... that might be part of what i have not correctly imported / configured??
I did the npm ... install -- save for each of them

thanks for any advide or hints on what i need to look at.

**Comment by figuerres** [comment]
Ahhhh   --- i think i see some of what is going on for me.
your sample seems to not be using the npm package for the oidc client that wants babel
you pulled the  minified js file and put that in a folder.
so you also do not have a babel module ....

**Comment by jmurphzyo** [comment]
@figuerres there was another issue posted about using systemjs but the title did not mention it,here is the link #5 . Currently I have a few projects that are getting close to their deadlines but once they are complete I will make a separate branch for systemjs.  You are correct about the min version I did a copy and paste for the oidc.client. If the link above doesn't help you out post what your systemjs.config, index.html, and package.json. That will give me a little insight of what the problem is.

**Comment by figuerres** [comment]
thanks for the reply !
here is a big question: your sample does not - as far as i can see use the bable-polyfill that is refered to on the https://github.com/IdentityModel/oidc-client-js
pages.
do i need that with angular 2 at all ??
if not then i can remove the package and that might also be the source of the errors i am seeing.
I think i have the js libary refered to in my systemjs right now in the right way.
I am going to pull the babel and see what happens....

**Comment by jmurphzyo** [comment]
You don't need to include the bable-polyfill in your project json, the reason for this is because the oidc-client already includes it within its package.json. [seen here](https://github.com/IdentityModel/oidc-client-js/blob/dev/package.json#L36)

**Comment by figuerres** [comment]
will comment on that side that they have some confusing docs then, they talk about needing to go get it and install it.
i am sorry that is not well worded, on the site for https://github.com/IdentityModel/oidc-client
I need to leave them feedback, they have documentation that says that i need to install the polyfill and the js library.  if it has it then ??? why would i get and install it again?

**Comment by figuerres** [comment]
I think i have it figured out now and starting to work.
as soon as i can i will copy my project and strip it down to the minimal files and we can post it somewhere up here. i am also going to let the thnkiture guys know also ...

most of your code worked but i did need a few tweaks... 
the polyfill.ts file has two lines i commented out.
and my router is a module    small stuff just took time to figure it out.

**Comment by jmurphzyo** [comment]
@figuerres  good to hear! Let me know if there is anything else I can help out with.
