### ISSUE TITLE
Internet Explorer 11

### ISSUE THREAD

**Issue by dbratsun** [jmurphzyo/Angular2OidcClient#7]
Don't work with IE 11

Error: Object doesn't support property or method 'from' 
Code: auth.html, line 13,
File: oidc-client.min.js, Line: 1, Column: 1665

**Comment by figuerres** [comment]
is it working in edge and chrome ??

**Comment by crh225** [comment]
I based my project off of this one and it works in IE11.

**Comment by dbratsun** [comment]
Yes, it works on edge & chrome

**Comment by figuerres** [comment]
Check on shim code for angular 2, there are posts on the angular 2 code site about issues with Internet Explorer. See if you can run a sample angular 2 app in ie at all. My project runs fine in chrome but has issues in ie 11 with js

**Comment by jmurphzyo** [comment]
@dbratsun I haven't tested this yet but the oidc-client.min.js file might be out of date. I physical copied the file locally it wasn't part of the build process. Once angular-cli makes their config more customizable I will update that file to copy during the build process so when the library updates that file will as well. Once again tho I haven't tested changing the file to see if it fixes your issue but its worth a try.

**Comment by jmurphzyo** [comment]
@dbratsun Did either of the above fix this issue? if not let me know and I will reopen.
