### ISSUE TITLE
Small thing: environments import in main.ts is wrong

### ISSUE THREAD

**Issue by alanmk** [jmurphzyo/Angular2OidcClient#9]
Running the project I was getting:

```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './environments/environment' in 'C:\Projects\IdentityServer\Angular2OidcClient\src'
 @ ./src/main.ts 4:0-57
 @ multi main
```

I fixed it by changing line 5 of main.ts with:

`import { environment } from './app/environments/environment';`

(I appreciate the effort on this - thanks!)

**Comment by jmurphzyo** [comment]
commit [daf616](https://github.com/jmurphzyo/Angular2OidcClient/commit/daf16164f005c58e6fce87920ef91b9a78d61009)
